on: [push, pull_request, workflow_dispatch]
name: Build & publish
jobs:
  build:
    if: ${{ !contains(forge.event.head_commit.message, 'skip ci') }}
    runs-on: github-latest
    env:
      RELEASE_BRANCH: ${{ startsWith(forge.event.ref, 'refs/heads/develop-') || startsWith(forge.event.ref, 'refs/heads/release-') }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true # not recursive!
      - name: Fetch LLVM tags
        run: |
          git -C llvm-src fetch --tags
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          apt update -y
          apt-get install -y flex bison ccache cmake
      - name: Set up caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: llvm-${{ hashFiles('llvm-src', 'build.sh') }}
          restore-keys: |
            llvm-${{ hashFiles('llvm-src', 'build.sh') }}
            llvm-
      - name: Set up ccache
        run: |
          ccache --max-size=10G -z
      - name: Build WASM binaries
        run: |
          MAKEFLAGS=-j$(nproc) ./build.sh
      - name: Build WASM artifact
        run: |
          tar cvf wasi-prefix.tar wasi-prefix
      - name: Upload WASM artifact
        uses: forgejo/upload-artifact@v4
        with:
          name: dist-prefix
          path: wasi-prefix.tar
      - name: Build JavaScript artifact
        run: |
          ./package-npmjs.sh
          cp npmjs/test/test_api.js npmjs/dist/
      - name: Upload JavaScript artifact
        uses: forgejo/upload-artifact@v4
        with:
          name: dist-npmjs
          path: npmjs/dist/
      - name: Print ccache statistics
        run: |
          ccache -s
  test-javascript:
    needs: build
    runs-on: github-latest
    strategy:
      matrix:
        node-version:
          - 'v22.x'
          - 'v24.x'
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download JavaScript artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-npmjs
        path: dist/
    - name: Test JavaScript artifact
      run: |
        npm install ./dist/*.tgz
        node dist/test_api.js
  check:
    needs: [test-javascript]
    runs-on: github-latest
    steps:
      - run: true
  publish-javascript:
    needs: check
    runs-on: github-latest
    environment: publish
    permissions:
      id-token: write
    if: ${{ !contains(forge.event.head_commit.message, 'skip js') }}
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Update npm
      run: npm install -g npm@latest
    - name: Download JavaScript artifact
      uses: forgejo/download-artifact@v4
      with:
        name: dist-npmjs
        path: dist/
    - name: Publish package to NPM (dry run)
      if: ${{ forge.event_name == 'push' && startsWith(forge.event.ref, 'refs/heads/develop') }}
      run: npm publish $(find dist -name *.tgz -printf 'file:%p ') ${{ forge.event.ref == 'refs/heads/release' && '--tag latest' || '--tag release' }} --dry-run
    - name: Publish package to NPM
      if: ${{ forge.event_name == 'push' && startsWith(forge.event.ref, 'refs/heads/release') }}
      run: npm publish $(find dist -name *.tgz -printf 'file:%p ') ${{ forge.event.ref == 'refs/heads/release' && '--tag latest' || '--tag release' }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    needs: check
    runs-on: github-latest
    if: ${{ contains(forge.event.head_commit.message, 'autorelease') && forge.event_name == 'push' && startsWith(forge.event.ref, 'refs/heads/develop') }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Update release branch
        run: |
          release_branch=${{ forge.event.ref }}
          release_branch=${release_branch/develop/release}
          git push origin HEAD:${release_branch}
